
---
language: python
python:
- 2.7
services: docker
before_install:
- sudo apt-get update
- sudo apt-get install python3
- sudo apt-get install pip3
install:
- git clone --recursive https://github.com/systemslab/popper /tmp/popper
- export PATH=$PATH:/tmp/popper/cli/bin
script: popper run
env:
  - N_REPETITIONS: 5
