
---
language: python
python:
- 2.7
services: docker
before_install:
- sudo add-apt-repository ppa:jonathonf/python-3.6
- sudo apt-get update
- sudo apt-get install python3.6
- sudo apt-get install python3-pip
install:
- git clone --recursive https://github.com/systemslab/popper /tmp/popper
- export PATH=$PATH:/tmp/popper/cli/bin
script: popper run
env:
  - N_REPETITIONS: 5
